//
//  ActionViewController.swift
//  Project16Extension
//
//  Created by Jacques on 17/02/16.
//  Copyright © 2016 J4SOFT. All rights reserved.
//

import UIKit
import MobileCoreServices

class ActionViewController: UIViewController {

    @IBOutlet weak var script: UITextView!
    var pageTitle = ""
    var pageURL = ""

    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Required to have the text in the UITextView at the top.
        // else some extra space is added at the top.
        self.automaticallyAdjustsScrollViewInsets = false

        // Default template code generated by Xcode.
//        // Get the item[s] we're handling from the extension context.
//        
//        // For example, look for an image and place it into an image view.
//        // Replace this with something appropriate for the type[s] your extension supports.
//        var imageFound = false
//        for item: AnyObject in self.extensionContext!.inputItems {
//            let inputItem = item as! NSExtensionItem
//            for provider: AnyObject in inputItem.attachments! {
//                let itemProvider = provider as! NSItemProvider
//                if itemProvider.hasItemConformingToTypeIdentifier(kUTTypeImage as String) {
//                    // This is an image. We'll load it, then place it in our image view.
//                    weak var weakImageView = self.imageView
//                    itemProvider.loadItemForTypeIdentifier(kUTTypeImage as String, options: nil, completionHandler: { (image, error) in
//                        NSOperationQueue.mainQueue().addOperationWithBlock {
//                            if let strongImageView = weakImageView {
//                                strongImageView.image = image as? UIImage
//                            }
//                        }
//                    })
//                    
//                    imageFound = true
//                    break
//                }
//            }
//            
//            if (imageFound) {
//                // We only handle one image, so stop looking for more.
//                break
//            }
//        }
        
        // Custom simplified code for the purpose of this extension.
        if let inputItem = extensionContext!.inputItems.first as? NSExtensionItem {
            if let itemProvider = inputItem.attachments?.first as? NSItemProvider {
                itemProvider.loadItemForTypeIdentifier(kUTTypePropertyList as String, options: nil)
                { [unowned self] (dict, error) in
                    let itemDictionary = dict as! NSDictionary
                    let javaScriptValues = itemDictionary[NSExtensionJavaScriptPreprocessingResultsKey] as! NSDictionary
                    
                    self.pageTitle = javaScriptValues["title"] as! String
                    self.pageURL = javaScriptValues["URL"] as! String
                    
                    dispatch_async(dispatch_get_main_queue()) {
                        // No need to specify a capture list ([unowned self]) for self 
                        // because we are already in a closure that specifies that.
                        self.title = self.pageTitle
                    }
                }
            }
        }
        
        // Registering for keyboard notifications.
        let notificationCenter = NSNotificationCenter.defaultCenter()
        // Don't forget the ":" at the end in "adjustForKeyboard:".
        notificationCenter.addObserver(self, selector: "adjustForKeyboard:", name: UIKeyboardWillHideNotification, object: nil)
        notificationCenter.addObserver(self, selector: "adjustForKeyboard:", name: UIKeyboardWillChangeFrameNotification, object: nil)
    }
    
    // Used to adjust the text view content inset to the keyboard.
    func adjustForKeyboard(notification: NSNotification) {
        let userInfo = notification.userInfo!
        
        // Getting information about the keyboad location and size.
        let keyboardScreenEndFrame = (userInfo[UIKeyboardFrameEndUserInfoKey] as! NSValue).CGRectValue()
        
        // Converting the keyboard coordinates into the ones of the view.
        let keyboardViewEndFrame = view.convertRect(keyboardScreenEndFrame, fromView: view.window)
        
        // Calculates the text view (script) content inset based on whether the keyboard is visible or not.
        if notification.name == UIKeyboardWillHideNotification {
            script.contentInset = UIEdgeInsetsZero
        } else {
            script.contentInset = UIEdgeInsets(top: 0, left: 0, bottom: keyboardViewEndFrame.height, right: 0)
        }
        
        // Updates the text view (script) scroll indicator insets
        script.scrollIndicatorInsets = script.contentInset
        
        // Scrolls the text view to the selected text.
        let selectedRange = script.selectedRange
        script.scrollRangeToVisible(selectedRange)
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }

    @IBAction func done() {
        // Passing back the value of the text view (script) to Safari, actually the Action.js finalize method.
        let item = NSExtensionItem()
        let webDictionary = [NSExtensionJavaScriptFinalizeArgumentKey: ["customJavaScript": script.text]]
        let customJavaScript = NSItemProvider(item: webDictionary, typeIdentifier: kUTTypePropertyList as String)
        item.attachments = [customJavaScript]
        
        extensionContext!.completeRequestReturningItems([item], completionHandler: nil)
    }
}
